-- 1. Creamos el entorno de BAZ
CREATE OR REPLACE DATABASE BAZ_BILLING_DB;
CREATE OR REPLACE SCHEMA BRONZE;

-- 2. La tabla Bronze para el JSON crudo
CREATE OR REPLACE TABLE BAZ_BILLING_DB.BRONZE.STG_FACTURACION_RAW (
    RAW_JSON VARIANT,
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_FILE STRING
);

-- 3. Creamos el Formato de Archivo
CREATE OR REPLACE FILE FORMAT BAZ_BILLING_DB.BRONZE.JSON_FORMAT
    TYPE = 'JSON'
    STRIP_OUTER_ARRAY = TRUE;