USE DATABASE BAZ_BILLING_DB;
USE SCHEMA SILVER;

CREATE OR REPLACE VIEW BAZ_BILLING_DB.SILVER.VW_REPORTE_FACTURACION 
COMMENT = 'Vista optimizada para reporteo de ingresos/egresos de BAZ. Une encabezado y detalle.'
AS
SELECT 
    E.FECHA,
    E.EMISOR_NOMBRE,
    E.RECEPTOR_NOMBRE,
    D.DESCRIPCION,
    D.CANTIDAD,
    D.IMPORTE,
    E.TOTAL AS TOTAL_FACTURA,
    -- Cálculo de impuesto para demostrar lógica de negocio
    ROUND(D.IMPORTE * 0.16, 2) AS IVA_CALCULADO
FROM BAZ_BILLING_DB.SILVER.FACTURAS_ENCABEZADO E
JOIN BAZ_BILLING_DB.SILVER.FACTURAS_DETALLE D ON E.ID_FACTURA = D.ID_FACTURA;