-- 1. Crear el entorno de trabajo
CREATE OR REPLACE DATABASE BAZ_BILLING_DB;
CREATE OR REPLACE SCHEMA BRONZE;

-- 2. Crear la tabla Bronze
CREATE OR REPLACE TABLE BAZ_BILLING_DB.BRONZE.STG_FACTURACION_RAW (
    RAW_JSON VARIANT,
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FILE_NAME STRING
);

-- 3. Crear un Formato de Archivo para JSON
CREATE OR REPLACE FILE FORMAT BAZ_BILLING_DB.BRONZE.JSON_FORMAT
    TYPE = 'JSON'
    STRIP_OUTER_ARRAY = TRUE;